export const regions = [
  'All States',
  'California',
  'Texas',
  'Florida',
  'New York',
  'Illinois',
  'Georgia',
  'Pennsylvania',
  'Ohio',
  'North Carolina',
  'Tennessee',
  'New Jersey',
  'Michigan',
  'Arizona',
  'Indiana',
  'Virginia',
  'South Carolina',
  'Missouri',
  'Massachusetts',
  'Wisconsin',
  'Alabama',
  'Louisiana',
  'Minnesota',
  'Kentucky',
  'Colorado',
  'Washington',
  'Oklahoma',
  'Maryland',
  'Utah',
  'Arkansas',
  'Mississippi',
  'Iowa',
  'Nevada',
  'Kansas',
  'Connecticut',
  'Oregon',
  'Nebraska',
  'New Mexico',
  'Idaho',
  'West Virginia',
  'Puerto Rico',
  'Rhode Island',
  'Montana',
  'South Dakota',
  'Delaware',
  'North Dakota',
  'New Hampshire',
  'Alaska',
  'Wyoming',
  'Maine',
  'Hawaii',
  'District of Columbia',
  'Vermont',
  'Guam',
  'Virgin Islands',
  'Northern Mariana Islands',
  'Grand Princess',
  'Diamond Princess',
];

export const time = ['All Time', 'Last Month', 'Last 7 days'];
